name: "When a release tag is created, build and publish a new version of the container image"

on: push

jobs:

  build-and-push-container-image:

    runs-on: ubuntu-latest

    # if: startsWith(github.ref, 'refs/tags/v')

    env:
      DOCKER_USER: smontrimewo
      GIT_USER: smontri-mewo
      CONTAINER_REGISTRY: docker.io
      CONTAINER_IMAGE: smontrimewo/hello-kubernetes
      GIT_REPOSITORY: git@github.com:smontri-mewo/hello-kubernetes.git
      CD_CHART_REPO: deploy/helm/hello-kubernetes
      CD_MANIFEST_FILE: Chart.yaml


    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image and version variables
        run: |
          echo "IMAGE=$CONTAINER_REGISTRY/$CONTAINER_IMAGE" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$(cat src/app/package.json | jq -r .version)" >> $GITHUB_ENV
          
      - name: Build additional image tag variables
        run: |
          echo "IMAGE_MAJOR_VERSION=$(echo $IMAGE_VERSION | cut -d '.' -f1)" >> $GITHUB_ENV
          echo "IMAGE_MINOR_VERSION=$(echo $IMAGE_VERSION | cut -d '.' -f2)" >> $GITHUB_ENV

      - name: Build image
        run: | 
          docker build --tag "$IMAGE:$IMAGE_VERSION" \
            --build-arg IMAGE_VERSION="$IMAGE_VERSION" \
            --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" \
            --file src/app/Dockerfile src/app

      - name: Create additional image tags
        run: |
          docker tag $IMAGE:$IMAGE_VERSION $IMAGE:$IMAGE_MAJOR_VERSION
          docker tag $IMAGE:$IMAGE_VERSION $IMAGE:$IMAGE_MAJOR_VERSION.$IMAGE_MINOR_VERSION

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image and tags to registry
        run: |
          docker push $IMAGE:$IMAGE_VERSION
          docker push $IMAGE:$IMAGE_MAJOR_VERSION
          docker push $IMAGE:$IMAGE_MAJOR_VERSION.$IMAGE_MINOR_VERSION
      
      - name: update Helm
        run: |
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_USER"@github.com"
          git clone https://smontri-mewo:${{ secrets.TOKEN }}@github.com/smontri-mewo/hello-helm.git
          ls hello-helm
          cd hello-helm
          docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace --verbose $CD_MANIFEST_FILE appVersion $IMAGE_VERSION
          git commit -am "update chart.yaml"
          git push